### PR TITLE
Remove libco + fix tiny emscripten [don't merge yet , more tests needed]

### PR DESCRIPTION
**Pull request by r-type**
@twinaphex @fr500 how do you feel about remove libco for 2014 ?

I've quickly tested on linux,android (ume build) and emscripten (tiny build ) seems to work .
but it need more test on windows .

### CODE REVIEW

**Comment by inactive123** [comment]
Very cool. I'll ask @fr500 if he can test on Windows.

**Comment by inactive123** [comment]
@-type Can you rebase this against mame 2014 current master? Getting lots of linking errors here trying to compile MAME -

http://hastebin.com/erusajonel.rb

**Comment by andres-asm** [comment]
Doesn't build

sdmodule.o obj//osd/modules/sync/work_osd.o obj//osd/modules/sync/sync_retro.o  -lws2_32 -lpthread -o mame2014_libretro.dll
make: execvp: g++: Argument list too long
make: *** [Makefile:892: mame2014] Error 127

**Comment by r-type** [comment]
@twinaphex  yes i get the same link error if i build mame , only TARGET=ume  or SUBTARGET=tiny build fine for me.
@fr500 the above commit should fix your error. but same as above try a TARGET=ume build.

but I’m afraid that it's already up to date with current master. https://github.com/r-type/mame2014-libretro/commit/b294d1975aadd7cec6749044f4fb1ec94acbff2a
i ll take a look to see if i can fix mame and mess link error.

**Comment by inactive123** [comment]
Yes, it has to work for both mame and mess targets before we are able to safely merge this, or indeed, test it on Windows [for @fr500 ]

**Comment by r-type** [comment]
[ for @twinaphex ]
not nice to tell it"s a waste of time to test my PR and discourage others from doing so !
Did not I spend personally the time to create/fix/enhance some repositories here ?

@other 
with the last commit all build should be fixed now , win/lin/andoid/emscripten ...
but I need test to see if there are regressions without libco

**Comment by inactive123** [comment]
@r-type Whoa hold on, you are getting this totally the wrong way. How on Earth could you think I was dissing you? I LOVE this PR and I love the changes you made. Sorry if I didn't make that clear before. Please don't assume ill intent where there is none meant or intended.

I just tested it on Linux and i works fine. I am willing to take the risk and assume based on my testing that there are no real problems remaining and merge this. If there are any issues, I'm sure can fix them later. There seems to be nothing major deal breaking remaining at least.

**Comment by inactive123** [comment]
BTW @r-type, do you think you could do the same for MAME 2010? I think it would be great to be able to remove libco there as well.

**Comment by r-type** [comment]
OK sorry  so I didn't understand very  well the  "or indeed, test it on Windows [for @fr500 ]" 

For the testing part ,  I mean and hope I exit cleanly and that there is no memory leak ect ...

For 2010 , yes it's possible, I done it some time ago for emscripten purpose.
I have now to search to find where I put it.

**Comment by inactive123** [comment]
Hi @r-type, 

yeah I can assure you that my remark wasn't meant to discourage anybody from being able to test it, not at all! I very much like the work you did with this PR and I was hoping we could get to merge it as soon as possible since I also think libco holds back the MAME port's development.

So I'm glad at least you mentioned it since I wouldn't have wanted you to hold onto some grudge and for me not to know what it was about. 

I'll very much look forward to seeing the same thing done for MAME 2010. Very good work you did.

**Pull request merged**
